Update initrd helper scripts

diff --git a/scripts/copy-initrd-modules b/scripts/copy-initrd-modules
--- a/scripts/copy-initrd-modules
+++ b/scripts/copy-initrd-modules
@@ -1,7 +1,9 @@
 #!/bin/bash
 
 ME=${0##*/}
-MP_ARGS="-D -a"
+# shellcheck disable=SC2034  # kept for parity with sibling scripts
+VERSION="26.04"
+MP_ARGS=(-D -a)
 
 usage() {
         cat <<Usage
@@ -34,7 +36,7 @@ Options:
     -v --verbose       List modules as they are copied
 
 Usage
-    exit ${1:-0}
+    exit "${1:-0}"
 }
 
 DEFAULT_LIST="
@@ -178,21 +180,23 @@ main() {
     local to_dir from_dir kernel
 
     local short_stack="defhkOpqQstv"
-    while [ $# -gt 0 -a -n "$1" -a -z "${1##-*}" ]; do
+    while [[ $# -gt 0 ]] && [[ -n "$1" ]] && [[ -z "${1##-*}" ]]; do
         local arg=${1#-} val=
         shift
 
         case $arg in
             [$short_stack][$short_stack]*)
                 if echo "$arg" | grep -q "^[$short_stack]\+$"; then
-                    set -- $(echo $arg | sed -r 's/([a-zA-Z])/ -\1 /g') "$@"
+                    local ARGS=()
+                    read -ra ARGS < <(echo "$arg" | sed -r 's/([a-zA-Z])/ -\1 /g')
+                    set -- "${ARGS[@]}" "$@"
                     continue
                 fi;;
         esac
 
         case $arg in
             -dir|-from|-kernel|-to|[dfkt])
-                [ $# -lt 1 ] && fatal "Expected a parameter after: -$arg"
+                [[ $# -lt 1 ]] && fatal "Expected a parameter after: -$arg"
                 val=$1
                 shift;;
             *=*)
@@ -205,9 +209,9 @@ main() {
         case $arg in
                   -) USE_STDIN=true                  ;;
            -count|c) SHOW_COUNT=true                 ;;
-             -dir|d) DIRS="$DIRS,$val"               ;;
+             -dir|d) DIRS="${DIRS:+$DIRS,}$val"       ;;
          -encrypt|e) ADD_ENCRYPT=true                ;;
-            -help|h) usage                           ;;
+            -help|h) usage 0                         ;;
             -from|f) from_dir=${val%/}               ;;
           -kernel|k) kernel=$val                     ;;
     -only-encrypt|O) ONLY_ENCRYPT=true               ;;
@@ -221,19 +225,21 @@ main() {
         esac
     done
 
-    [ "$QUIET" -o "$VERY_QUIET" ] && MP_ARGS="$MP_ARGS --quiet"
+    { [[ "$QUIET" ]] || [[ "$VERY_QUIET" ]]; } && MP_ARGS+=(--quiet)
     # fill in default kernel if there is only one
-    if [ -z "$kernel" ]; then
+    if [[ -z "$kernel" ]]; then
         local d="$from_dir/lib/modules"
         test -d "$d" || fatal "Could not find directory \"$d\""
-        [ "$(ls "$d" | wc -l)" = 1 ] && kernel=$(ls "$d")
+        local kernels=()
+        readarray -t kernels < <(find "$d" -mindepth 1 -maxdepth 1 -printf '%f\n')
+        [[ ${#kernels[@]} -eq 1 ]] && kernel=${kernels[0]}
     fi
 
-    [ "$kernel"   ] && MP_ARGS="$MP_ARGS -S $kernel"
-    [ "$from_dir" ] && MP_ARGS="$MP_ARGS -d \"$from_dir\""
+    [[ "$kernel" ]] && MP_ARGS+=(-S "$kernel")
+    [[ "$from_dir" ]] && MP_ARGS+=(-d "$from_dir")
 
-    : ${kernel:=$(uname -r)}
-    : ${to_dir:=.}
+    : "${kernel:=$(uname -r)}"
+    : "${to_dir:=.}"
 
     local mod_dir="$from_dir/lib/modules/$kernel"
     test -d "$mod_dir" || fatal "Directory $mod_dir does not exist"
@@ -241,22 +247,23 @@ main() {
     local list1 list2 repeats default_mode
     # grab list from files or stdin and strip comments
 
-    if [ "$ADD_ENCRYPT" ]; then
+    if [[ "$ADD_ENCRYPT" ]]; then
         DEFAULT_LIST=$DEFAULT_LIST$CRYPT_LIST
-    elif [ "$ONLY_ENCRYPT" ]; then
+    elif [[ "$ONLY_ENCRYPT" ]]; then
         DEFAULT_LIST=$CRYPT_LIST
     fi
 
-    if [ -z "$USE_STDIN" -a $# -eq 0 ]; then
+    if [[ -z "$USE_STDIN" ]] && [[ $# -eq 0 ]]; then
         default_mode=true
         list1=$(echo "$DEFAULT_LIST" | grep -v "^\s*#" | sed 's/\s*#.*//')
     else
         list1=$(cat "$@" | grep -v "^\s*#" | sed -e 's/\s*#.*//' -e "s/,/ /g")
     fi
 
-    [ "$default_mode" -a -z "$DIRS" ] && DIRS="kernel/drivers/ata kernel/drivers/mmc"
-    local d
-    for d in $(echo $DIRS | sed 's/,/ /g'); do
+    [[ "$default_mode" ]] && [[ -z "$DIRS" ]] && DIRS="kernel/drivers/ata,kernel/drivers/mmc"
+    local d dir_array=()
+    [[ -n "$DIRS" ]] && IFS=', ' read -ra dir_array <<< "$DIRS"
+    for d in "${dir_array[@]}"; do
         local dir=$mod_dir/$d
         test -d "$dir" || fatal "Subdirectory $dir does not exist"
         list1="$list1
@@ -264,45 +271,51 @@ $(find "$dir" -type f -name '*\.ko*' -printf "%f\n" | sed -nr 's/\.ko(|\.[[:alph
     done
 
     repeats=$(echo "$list1" | sed 's/_/-/g' | sort | uniq --repeated | grep .)
-    if [ "$repeats" -a -z "$VERY_QUIET" ]; then
-        local cnt=$(echo "$repeats" | wc -l)
+    if [[ "$repeats" ]] && [[ -z "$VERY_QUIET" ]]; then
+        local cnt
+        cnt=$(echo "$repeats" | wc -l)
         warn "$cnt repeated module(s) in input"
         echo "$repeats" >&2
     fi
 
     list2=$(echo "$list1" | sed 's/_/-/g' | sort -u \
-        | eval "xargs /sbin/modprobe -n $MP_ARGS" | sed -n 's/^insmod //p' |cut -d' ' -f1| sort -u)
+        | xargs /sbin/modprobe -n "${MP_ARGS[@]}" | sed -n 's/^insmod //p' | cut -d' ' -f1 | sort -u)
 
     local full cnt=0
-    [ -z "${from_dir##/*}" ] || from_dir="$PWD/$from_dir"
-    while read full; do
-        [ "$VERBOSE" ] && printf "  %s\n" "$(basename "$full")"
-        local dir=$(dirname "$full")
-        dir="$to_dir/${dir##$from_dir/}"
-        test -d "$dir" || echo_cmd mkdir -p "$dir"
-        echo_cmd cp "$full" "$dir/"
+    [[ -z "${from_dir##/*}" ]] || from_dir="$PWD/$from_dir"
+    while read -r full; do
+        [[ "$VERBOSE" ]] && printf "  %s\n" "$(basename "$full")"
+        local dir
+        dir=$(dirname "$full")
+        dir="$to_dir/${dir##"$from_dir"/}"
+        test -d "$dir" || pretend mkdir -p "$dir"
+        pretend cp "$full" "$dir/"
         cnt=$((++cnt))
     done<<List_2
-$(echo "$list2")
+$list2
 List_2
 
-    [ "$SHOW_COUNT" ] && printf "$ME: %s module(s)\n" "$cnt"
+    [[ "$SHOW_COUNT" ]] && printf '%s: %s module(s)\n' "$ME" "$cnt"
 
     exit 0
 }
 
-echo_cmd() {
-    [ "$PRETEND" ] && return
+pretend() {
+    [[ "$PRETEND" ]] && return
     "$@"
 }
 
 fatal() {
-    echo "$ME error: $*" >&2
+    local fmt=$1; shift
+    # shellcheck disable=SC2059
+    printf "$ME fatal error: $fmt\n" "$@" >&2
     exit 3
 }
 
 warn() {
-    echo "$ME warning: $*" >&2
+    local fmt=$1; shift
+    # shellcheck disable=SC2059
+    printf "$ME warning: $fmt\n" "$@" >&2
 }
 
 main "$@"
